service: unimonitor-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: prod
  region: sa-east-1
  memorySize: 128

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline
